<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="DocumentFormat.OpenXml" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Serilog" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\BackendCarcass\BackendCarcass.Application\BackendCarcass.Application.csproj" />
        <ProjectReference Include="..\..\MimosiGeCore\MimosiGeCore.Application.Abstractions\MimosiGeCore.Application.Abstractions.csproj" />
        <ProjectReference Include="..\AppMimosiGe.Application\AppMimosiGe.Application.csproj" />
    </ItemGroup>
</Project>
