<?xml version="1.0" encoding="utf-8"?><Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Figgle.Fonts" Version="0.6.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.21.0.135717" />
  </ItemGroup>
</Project>