<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <Folder Include="Installers\" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="BackendCarcass.Repositories" />
      <PackageReference Include="BackendCarcass.Rights" />
      <PackageReference Include="MimosiGeDbPart.Db" />
    </ItemGroup>
</Project>