<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
      <PackageReference Include="BackendCarcass.Api" />
      <PackageReference Include="BackendCarcass.Application" />
      <PackageReference Include="BackendCarcass.Repositories" />
      <PackageReference Include="Figgle.Fonts" />
      <PackageReference Include="MimosiGeDbPart.Db" />
      <PackageReference Include="WebSystemTools.ConfigurationEncrypt" />
      <PackageReference Include="WebSystemTools.MediatorTools" />
      <PackageReference Include="WebSystemTools.SerilogLogger" />
      <PackageReference Include="WebSystemTools.SwaggerTools" />
      <PackageReference Include="WebSystemTools.TestToolsApi" />
      <PackageReference Include="WebSystemTools.WindowsServiceTools" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\AppMimosiGeRepositories\AppMimosiGeRepositories.csproj" />
    </ItemGroup>
    <PropertyGroup>
        <UserSecretsId>245797f3-a8f3-4898-bd90-48b87927e5fc</UserSecretsId>
    </PropertyGroup>
</Project>